language: node_js

node_js:
  - 4

notifications:
  email:
    recipients:
      - ilanguagelab-dev@googlegroups.com
    on_success: change
    on_failure: always

before_script:
  - export CHROME_BIN=chromium-browser
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - cd app

before_install:
  # Download and configure deps
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g jasmine-node
  - pwd
  - ls bower.json && bower install
  # Make sure the emulator has started before running tests

script:
  - grunt travis
